// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using template_csharp_album_collections;

namespace template_csharp_album_collections.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220317190904_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("template_csharp_album_collections.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Born in compton",
                            Genre = "Rap",
                            HeroImage = "/images/kendrick.jpg",
                            Name = "Kendrick Lamar"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Daughter of Billy Ray",
                            Genre = "Pop",
                            HeroImage = "/images/miley.jpg",
                            Name = "Miley Cyrus"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Abel Makkonen Tefaye, Known professionally as the Weekend",
                            Genre = "R&B",
                            HeroImage = "/images/theweekend.webp",
                            Name = "The Weekend"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
