// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using template_csharp_album_collections;

namespace template_csharp_album_collections.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220323042652_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("template_csharp_album_collections.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Image = "https://m.media-amazon.com/images/I/71FvMBLmheL._SL1200_.jpg",
                            RecordLabel = "Aftermath",
                            Title = "DAMN."
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            Image = "https://i.pinimg.com/originals/38/e0/6e/38e06ed03db63c6d75338a5a76b3135b.png",
                            RecordLabel = "RCA Records",
                            Title = "Plastic Hearts"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            Image = "https://m.media-amazon.com/images/I/81-blrK5yoL._SL1400_.jpg",
                            RecordLabel = "XO",
                            Title = "House of Balloons"
                        });
                });

            modelBuilder.Entity("template_csharp_album_collections.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeroImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Born in compton",
                            Genre = "Rap",
                            HeroImage = "/images/kendrick.jpg",
                            Name = "Kendrick Lamar"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Daughter of Billy Ray",
                            Genre = "Pop",
                            HeroImage = "/images/miley.jpg",
                            Name = "Miley Cyrus"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Abel Makkonen Tefaye, Known professionally as the Weekend",
                            Genre = "R&B",
                            HeroImage = "/images/theweekend.webp",
                            Name = "The Weekend"
                        });
                });

            modelBuilder.Entity("template_csharp_album_collections.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Content = "My boyfriend fave album",
                            ReviewerName = "Miranda"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 2,
                            Content = "I really wish she could do better",
                            ReviewerName = "user05079786"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 3,
                            Content = "Love him!Praying for him every night<3",
                            ReviewerName = "TheWeekandJunkie"
                        });
                });

            modelBuilder.Entity("template_csharp_album_collections.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Title = "Loyalty ft. Rihanna"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            Title = "Lust"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 2,
                            Title = "Prisoner (FEAT. DUA LIPA)"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 2,
                            Title = "Angels Like You"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 3,
                            Title = "The Morning"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 3,
                            Title = "Wicked Games"
                        });
                });

            modelBuilder.Entity("template_csharp_album_collections.Models.Album", b =>
                {
                    b.HasOne("template_csharp_album_collections.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("template_csharp_album_collections.Models.Review", b =>
                {
                    b.HasOne("template_csharp_album_collections.Models.Album", "Album")
                        .WithMany("Reviews")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("template_csharp_album_collections.Models.Song", b =>
                {
                    b.HasOne("template_csharp_album_collections.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("template_csharp_album_collections.Models.Album", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Songs");
                });

            modelBuilder.Entity("template_csharp_album_collections.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
